//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumPoker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public Nullable<int> UserId { get; set; }
        public int ProjectId { get; set; }
        public string NickName { get; set; }
        public int id { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual UserProfileScrum UserProfile { get; set; }
    }
}
