//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumPoker
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileScrum
    {
        public UserProfileScrum()
        {
            this.UsersInRoles = new HashSet<UsersInRoles>();
            this.Projects = new HashSet<Project>();
            this.TeamMembers = new HashSet<TeamMember>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<UsersInRoles> UsersInRoles { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
    }
}
